CREATE TABLE PrivateInfo (
    [Id] INT IDENTITY(1,1) PRIMARY KEY,
    [UserId] INT NOT NULL CONSTRAINT FK_PrivateInfo_Users FOREIGN KEY REFERENCES users([Id]),
    [Type] NVARCHAR(50) NOT NULL,
    [Value] NVARCHAR(200) NOT NULL,
    [CreatedAt] DATETIME NOT NULL DEFAULT GETDATE()
);